<h1 style = "color:red">Delta Rule</h1>

**732_Saksham**


**Write a Program to implement Delta-Rule**

**w(new) = w(old) + Learning_rate * (desired_op - actual_op)**

In [1]:
import numpy as np

In [2]:
#  making 4 zeros array

In [3]:
x = np.zeros((3,))

# size 3 (zero ) array

In [4]:
weights = np.zeros((3,))

In [5]:
desired = np.zeros((3,))

In [6]:
actual = np.zeros((3,))

In [7]:
for i in range(0,3):
    x[i] = float(input("Initial Inputs : "))

Initial Inputs : 1
Initial Inputs : 1
Initial Inputs : 1


In [8]:
for i in range(0,3):
    weights[i] = float(input("Initial Weights : "))

Initial Weights : 1
Initial Weights : 1
Initial Weights : 1


In [9]:
for i in range(0,3):
    desired[i] = float(input("Desired Outputs : "))

Desired Outputs : 2
Desired Outputs : 3
Desired Outputs : 4


In [10]:
a = float(input("Enter learning rate : "))

Enter learning rate : 1


# Outputs : 

In [11]:
x

array([1., 1., 1.])

In [12]:
weights

array([1., 1., 1.])

In [13]:
desired

array([2., 3., 4.])

In [14]:
a

# learning rate

1.0

<hr>


**Lets build Neural Network**

In [15]:
actual = x * weights

In [16]:
# initially weight are 1 and inputs are also 1.

print("Actual output : ", actual)

print("Desired Output : ", desired)

Actual output :  [1. 1. 1.]
Desired Output :  [2. 3. 4.]


In [17]:
while True:
    if np.array_equal(desired, actual):
        break
    else:
        for i in range(0, 3):
            weights[i] = weights[i] + a * (desired[i] - actual[i])
            actual = x * weights
            

In [18]:
print("🔶Final Output : ")
print("Corrected weights: ",weights)
print("Actual outputs : ", actual)
print("Desired Output : ", desired)

🔶Final Output : 
Corrected weights:  [2. 3. 4.]
Actual outputs :  [2. 3. 4.]
Desired Output :  [2. 3. 4.]
