<h1 style = "color:red">Hebb Rule</h1>



meri marzi  😊


weights updation formula : 

- **Wi(new) = wi(old) + xi * y**

Bias Updation :

- **bias(new) = bias(old) + y**

In [1]:
import numpy as np

# First Pattern

In [2]:
x1 = np.array([1,1,1,-1,1,-1,1,1,1])

<pre>

x1 =  + | + | +
      ________
        | + | 
      ________
      + | + | +
      
      
</pre>

**here I am taking shape as "I"**


In [3]:
b = 0

# bias value = 0

In [4]:
y = np.array([1,-1])

y

# x1 = 1 (represents x1)
# x2 = -1

array([ 1, -1])

In [5]:
# array for weights [old and New]

# first initialize weights to zero(0)

wtold = np.zeros((9,))

wtnew = np.zeros((9,))

In [6]:
# weights data type int

wtnew = wtnew.astype(int)

wtold = wtold.astype(int)

In [7]:
wtnew

# initially weights are zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
wtold

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# weights updation rule

# first run loop for pattern x1 .
# To get pattern  = "I"
    
print("First input with target = 1")

for i in range(0,9):
    wtold[i] = wtold[i] + x1[i] * y[0]
    
b = b + y[0]



# y[0] = to call y[1, -1] (to call y = 1)

First input with target = 1


In [10]:
# weights and bias after first pattern matching

print("New Weights : ", wtnew)

print("Bias value : ", b)

New Weights :  [0 0 0 0 0 0 0 0 0]
Bias value :  1


# Second pattern

In [11]:
# creating second pattern x2 = "O"

x2 = np.array([1,1,1,1,-1,1,1,1,1])

x2

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1])

**Taking shape as " O "**

In [12]:
print("First input with target = -1")

for i in range(0,9):
    wtnew[i] = wtold[i] + x2[i] * y[1]
    
b = b + y[1]

First input with target = -1


# Final weights after both Pattern

In [13]:
print("New Weights : ", wtnew)

print("Bias value : ", b)

New Weights :  [ 0  0  0 -2  2 -2  0  0  0]
Bias value :  0


😒